### ISSUE TITLE
这个模型能不能只输出一个目标？

### ISSUE THREAD

**Issue by zhangyouchang** [xiaohu2015/DeepLearning_tutorials#4]
比如我想只对车进行画框，该如何操作？我把class里面除了车的去掉后会报错

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [539] rhs shape= [1470]

**Comment by xiaohu2015** [comment]
@zhangyouchang 修改绘图的代码不就可以了吗，屏蔽其它class

**Comment by qiang92** [comment]
比如yolo你把self.classes中只保留一个car就可以了。
兄弟你都有源代码了，都不看吗？
